### ISSUE TITLE
Alignment failed, list-style-type not align along with text

### ISSUE THREAD

**Issue by BDMChau** [microsoft/roosterjs#1160]
A bit hard to describe by text, so I put the video below.
It was still working on Firefox but failed on Chrome, Edge, and Safari. I relized the Alignment action put CSS properties differently on each browser.
When copy&paste from docx file, it failed on all browsers

https://user-images.githubusercontent.com/64347888/183111118-7ad34436-d442-40ee-bfce-a6f1dd5825d8.mp4

**Comment by romanisa** [comment]
@BDMChau this has been fixed in the latest version. Can you please check the version you are on?

**Comment by BDMChau** [comment]
@romanisa Yes, I'm using v8.28.1 and applied plugins like demo code on getToggleablePlugins.ts file
I saw on demo site it's still failed when copy&patse from word file

**Comment by BDMChau** [comment]
seem like my mistake, I forgot to add ExperimentalFeatures, but still failed when copy&paste from docx file

**Comment by JiuqingSong** [comment]
Can you provide a sample docx file?
